# -*- coding: utf-8 -*-
"""Tests_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ruj2uIGNdU8a0EjWGmpdy8BgNISaWUTA
"""

import unittest
from unittest.mock import patch, MagicMock
from vulnerable_app import app

class TestVulnerableApp(unittest.TestCase):

    def setUp(self):
        self.app = app.test_client()
        self.app.testing = True
        # Clave secreta para manejo de sesiones en tests
        app.secret_key = 'test_secret_key'

    @patch('vulnerable_app.get_db_connection')
    def test_index(self, mock_db):
        """Prueba que la página de inicio carga correctamente"""
        response = self.app.get('/')
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Welcome to the Task Manager Application!', response.data)

    @patch('vulnerable_app.get_db_connection')
    def test_login_page_loads(self, mock_db):
        """Prueba que la página de login carga el formulario"""
        response = self.app.get('/login')
        self.assertEqual(response.status_code, 200)
        self.assertIn(b'Username:', response.data)

    @patch('vulnerable_app.get_db_connection')
    def test_login_success_mock(self, mock_get_db):
        """Simula un login exitoso mockeando la base de datos"""
        # Configurar el mock de la DB
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_get_db.return_value = mock_conn
        mock_conn.cursor.return_value = mock_cursor

        # Simular usuario encontrado: (id, username, password, role)
        mock_cursor.fetchone.return_value = (1, 'admin', 'hash', 'admin')

        # En la lógica de tu app, a veces usa execute directo sobre conn o sobre cursor
        # Mockeamos ambos casos por seguridad
        mock_conn.execute.return_value.fetchone.return_value = (1, 'admin', 'hash', 'admin')

        response = self.app.post('/login', data=dict(
            username='admin',
            password='password123'
        ), follow_redirects=True)

        # Si el login funciona, debería redirigir o mostrar el dashboard
        # Nota: Tu código tiene print() que pueden salir en consola, es normal.
        self.assertEqual(response.status_code, 200)

    def test_dashboard_access_denied(self):
        """Prueba que no se puede entrar al dashboard sin loguearse"""
        response = self.app.get('/dashboard')
        self.assertEqual(response.status_code, 302) # Redirección
        self.assertIn('/login', response.headers['Location'])

if __name__ == '__main__':
    unittest.main()